services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php    
    tty: true
    expose:
      - ${PROD_PHP_EXPOSE}
    environment:
      - TZ=UTC
    depends_on:
      - db
    volumes:
      - ./app:/var/www/app

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    depends_on:
      - php
    ports:
      - ${PROD_APACHE_HTTP}:80
    environment:
      - TZ=UTC
      - VIRTUAL_HOST=${PROD_WWWROOT}      
    volumes:
      - ./app:/var/www/app      

  db:
    image: mariadb:lts-ubi9
    container_name: docker.mariadb    
    restart: always    
    ports:
      - ${PROD_DB_EXPOSE}:3306    
    environment:
      - TZ=UTC
      - MARIADB_ROOT_PASSWORD=${PROD_DBPASS}
      - HOSTNAME=localhost
    volumes:
      - ./db:/var/lib/mysql 
      - ./docker/mysql/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro

  adminer:
    image: adminer:5.3.0
    container_name: docker.adminer    
    restart: always
    ports:
      - ${PROD_ADMINER_EXPOSE}:8080
    environment:
      - TZ=UTC      
